### PR TITLE
Changing plotly newplot to plotly react.

### PR DESCRIPTION
**Pull request by Mynamewasused**
New Plot is expensive and discards event handlers, react is a better option.

### CODE REVIEW

**Comment by Bob-Thomas** [comment]
indeed like mentioned in #10

**Comment by manthey** [comment]
This also would fix issues #12 and #16.

**Comment by harryjubb** [comment]
@statnett @gwdekker @wendelborg any update on this?

**Comment by mokkabonna** [comment]
This PR broke the tests, the referenced commit also fixes tests. Data need to be immutable or datarevision need to be set. I chose the latter approach in watch handler for data.

**Pull request closed without merging**
